server:
  port: 8083

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri:
          lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizen/**

      - id: VACCINATION-CENTER-SERVICE
        uri:
          lb://VACCINATION-CENTER-SERVICE
        predicates:
        - Path=/vaccinationcenter/**


